In [25]:
import pandas as pd
import numpy as np
df1 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.RU.ZS_DS2_en_csv_v2_4364070.json')
df1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [26]:
df1 = df1.replace(r'^\s*$', np.nan, regex=True)
df1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,NaN
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,NaN
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,NaN
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,NaN,100,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,NaN,60.6768035888672,61.9411163330078,NaN,NaN
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,NaN
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,NaN
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,NaN

In [27]:
df1.fillna(0, inplace = True)
df1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,0.0
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,0.0
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,0.0
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,0,100,0,0.0,0.0
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,0,60.6768035888672,61.9411163330078,0.0,0.0
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,0.0
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,0.0
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,0.0

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    float64
 5   5       268 non-null    float64
 6   6       268 non-null    float64
 7   7       268 non-null    float64
 8   8       268 non-null    float64
 9   9       268 non-null    float64
 10  10      268 non-null    float64
 11  11      268 non-null    float64
 12  12      268 non-null    float64
 13  13      268 non-null    float64
 14  14      268 non-null    float64
 15  15      268 non-null    float64
 16  16      268 non-null    float64
 17  17      268 non-null    float64
 18  18      268 non-null    float64
 19  19      268 non-null    float64
 20  20      268 non-null    float64
 21  21      268 non-null    float64
 22  22      268 non-null    float64
 23  23      268 non-null    float64
 24  24      268 non-null    float64
 25  25      268 non-null    float64
 26  26      268 non-null    float64
 27  27      268 non-null    float64
 28  28      268 non-null    float64
 29  29      268 non-null    float64
 30  30      268 non-null    float64
 31  31      268 non-null    float64
 32  32      268 non-null    float64
 33  33      268 non-null    float64
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      268 non-null    object
 61  61      268 non-null    object
 62  62      268 non-null    object
 63  63      268 non-null    object
 64  64      268 non-null    object
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(32), object(35)
memory usage: 140.4+ KB

In [29]:
csvdf1 = df1.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.RU.ZS_DS2_en_csv_v2_4364070_csvfile.csv')
csvdf1

In [30]:
df2 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_4353549.json')
df2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [31]:
df2 = df2.replace(r'^\s*$', np.nan, regex=True)
df2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,NaN
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,NaN
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,NaN,100,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,NaN
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,NaN
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,NaN
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,NaN

In [32]:
df2.fillna(0, inplace = True)
df2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,0.0
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,0.0
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0.0,0.0
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,0,100,0,0.0,0.0
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,0.0,0.0
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,0.0,0.0
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,0.0,0.0
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,0.0,0.0

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    float64
 5   5       268 non-null    float64
 6   6       268 non-null    float64
 7   7       268 non-null    float64
 8   8       268 non-null    float64
 9   9       268 non-null    float64
 10  10      268 non-null    float64
 11  11      268 non-null    float64
 12  12      268 non-null    float64
 13  13      268 non-null    float64
 14  14      268 non-null    float64
 15  15      268 non-null    float64
 16  16      268 non-null    float64
 17  17      268 non-null    float64
 18  18      268 non-null    float64
 19  19      268 non-null    float64
 20  20      268 non-null    float64
 21  21      268 non-null    float64
 22  22      268 non-null    float64
 23  23      268 non-null    float64
 24  24      268 non-null    float64
 25  25      268 non-null    float64
 26  26      268 non-null    float64
 27  27      268 non-null    float64
 28  28      268 non-null    float64
 29  29      268 non-null    float64
 30  30      268 non-null    float64
 31  31      268 non-null    float64
 32  32      268 non-null    float64
 33  33      268 non-null    float64
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      268 non-null    object
 61  61      268 non-null    object
 62  62      268 non-null    object
 63  63      268 non-null    object
 64  64      268 non-null    object
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(32), object(35)
memory usage: 140.4+ KB

In [34]:
csvdf2 = df2.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_4353549.csv')
csvdf2

In [36]:
df3 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.UR.ZS_DS2_en_csv_v2_4367536.json')
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [37]:
df3 = df3.replace(r'^\s*$', np.nan, regex=True)
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,NaN
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,NaN
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,NaN
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,NaN,99.9000015258789,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,NaN,93.0709533691406,93.1134567260742,NaN,NaN
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,NaN
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,NaN
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,NaN

In [38]:
df3.fillna(0, inplace = True)
df3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,0.0
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,0.0
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0,0.0
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,0,99.9000015258789,0,0.0,0.0
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,0,93.0709533691406,93.1134567260742,0.0,0.0
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0.0,0.0
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0.0,0.0
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0.0,0.0

In [39]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    float64
 5   5       268 non-null    float64
 6   6       268 non-null    float64
 7   7       268 non-null    float64
 8   8       268 non-null    float64
 9   9       268 non-null    float64
 10  10      268 non-null    float64
 11  11      268 non-null    float64
 12  12      268 non-null    float64
 13  13      268 non-null    float64
 14  14      268 non-null    float64
 15  15      268 non-null    float64
 16  16      268 non-null    float64
 17  17      268 non-null    float64
 18  18      268 non-null    float64
 19  19      268 non-null    float64
 20  20      268 non-null    float64
 21  21      268 non-null    float64
 22  22      268 non-null    float64
 23  23      268 non-null    float64
 24  24      268 non-null    float64
 25  25      268 non-null    float64
 26  26      268 non-null    float64
 27  27      268 non-null    float64
 28  28      268 non-null    float64
 29  29      268 non-null    float64
 30  30      268 non-null    float64
 31  31      268 non-null    float64
 32  32      268 non-null    float64
 33  33      268 non-null    float64
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      268 non-null    object
 61  61      268 non-null    object
 62  62      268 non-null    object
 63  63      268 non-null    object
 64  64      268 non-null    object
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(32), object(35)
memory usage: 140.4+ KB

In [40]:
csvdf3 = df3.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.ACCS.UR.ZS_DS2_en_csv_v2_4367536.csv')
csvdf3

In [41]:
df4 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.LOSS.ZS_DS2_en_csv_v2_4357259.json')
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [42]:
df4 = df4.replace(r'^\s*$', np.nan, regex=True)
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,NaN
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df4.fillna(0, inplace = True)
df4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0,0,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,0.0
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,0,0,0,0,0,0,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    object
 5   5       268 non-null    object
 6   6       268 non-null    object
 7   7       268 non-null    object
 8   8       268 non-null    object
 9   9       268 non-null    object
 10  10      268 non-null    object
 11  11      268 non-null    object
 12  12      268 non-null    object
 13  13      268 non-null    object
 14  14      268 non-null    object
 15  15      268 non-null    object
 16  16      268 non-null    object
 17  17      268 non-null    object
 18  18      268 non-null    object
 19  19      268 non-null    object
 20  20      268 non-null    object
 21  21      268 non-null    object
 22  22      268 non-null    object
 23  23      268 non-null    object
 24  24      268 non-null    object
 25  25      268 non-null    object
 26  26      268 non-null    object
 27  27      268 non-null    object
 28  28      268 non-null    object
 29  29      268 non-null    object
 30  30      268 non-null    object
 31  31      268 non-null    object
 32  32      268 non-null    object
 33  33      268 non-null    object
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    float64
 60  60      268 non-null    float64
 61  61      268 non-null    float64
 62  62      268 non-null    float64
 63  63      268 non-null    float64
 64  64      268 non-null    float64
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(8), object(59)
memory usage: 140.4+ KB

In [46]:
csvdf4 = df4.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.LOSS.ZS_DS2_en_csv_v2_4357259.csv')
csvdf4

In [47]:
df5 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.NUCL.ZS_DS2_en_csv_v2_4357319.json')
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [48]:
df5 = df5.replace(r'^\s*$', np.nan, regex=True)
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,NaN
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.73257405151658,3.58003778041762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.5712660747575,5.52929999879746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df5.fillna(0, inplace = True)
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,0.0
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,3.73257405151658,3.58003778041762,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,5.5712660747575,5.52929999879746,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    object
 5   5       268 non-null    object
 6   6       268 non-null    object
 7   7       268 non-null    object
 8   8       268 non-null    object
 9   9       268 non-null    object
 10  10      268 non-null    object
 11  11      268 non-null    object
 12  12      268 non-null    object
 13  13      268 non-null    object
 14  14      268 non-null    object
 15  15      268 non-null    object
 16  16      268 non-null    object
 17  17      268 non-null    object
 18  18      268 non-null    object
 19  19      268 non-null    object
 20  20      268 non-null    object
 21  21      268 non-null    object
 22  22      268 non-null    object
 23  23      268 non-null    object
 24  24      268 non-null    object
 25  25      268 non-null    object
 26  26      268 non-null    object
 27  27      268 non-null    object
 28  28      268 non-null    object
 29  29      268 non-null    object
 30  30      268 non-null    object
 31  31      268 non-null    object
 32  32      268 non-null    object
 33  33      268 non-null    object
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      268 non-null    float64
 61  61      268 non-null    float64
 62  62      268 non-null    float64
 63  63      268 non-null    float64
 64  64      268 non-null    float64
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(7), object(60)
memory usage: 140.4+ KB

In [51]:
csvdf5 = df5.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.NUCL.ZS_DS2_en_csv_v2_4357319.csv')
csvdf5

In [52]:
df6 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.PETR.ZS_DS2_en_csv_v2_4356435.json')
df6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [53]:
df6 = df6.replace(r'^\s*$', np.nan, regex=True)
df6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,NaN
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df6.fillna(0, inplace = True)
df6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,0.0
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,0,0,0,0,0,0,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    object
 5   5       268 non-null    object
 6   6       268 non-null    object
 7   7       268 non-null    object
 8   8       268 non-null    object
 9   9       268 non-null    object
 10  10      268 non-null    object
 11  11      268 non-null    object
 12  12      268 non-null    object
 13  13      268 non-null    object
 14  14      268 non-null    object
 15  15      268 non-null    object
 16  16      268 non-null    object
 17  17      268 non-null    object
 18  18      268 non-null    object
 19  19      268 non-null    object
 20  20      268 non-null    object
 21  21      268 non-null    object
 22  22      268 non-null    object
 23  23      268 non-null    object
 24  24      268 non-null    object
 25  25      268 non-null    object
 26  26      268 non-null    object
 27  27      268 non-null    object
 28  28      268 non-null    object
 29  29      268 non-null    object
 30  30      268 non-null    object
 31  31      268 non-null    object
 32  32      268 non-null    object
 33  33      268 non-null    object
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      268 non-null    float64
 61  61      268 non-null    float64
 62  62      268 non-null    float64
 63  63      268 non-null    float64
 64  64      268 non-null    float64
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(7), object(60)
memory usage: 140.4+ KB

In [56]:
csvdf6 = df6.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.PETR.ZS_DS2_en_csv_v2_4356435.csv')
csvdf6

In [57]:
df7 = pd.read_json(r'C:\Users\hp\Downloads\API_EG.ELC.RNWX.KH_DS2_en_csv_v2_4356007.json')
df7

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [58]:
df7 = df7.replace(r'^\s*$', np.nan, regex=True)
df7

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,NaN
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df7.fillna(0, inplace = True)
df7

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,0.0
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.669000e+09,7.687000e+09,1.092600e+10,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.830000e+08,2.251000e+09,4.763000e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,1.660000e+08,1.440000e+08,1.290000e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    float64
 5   5       268 non-null    float64
 6   6       268 non-null    float64
 7   7       268 non-null    float64
 8   8       268 non-null    float64
 9   9       268 non-null    float64
 10  10      268 non-null    float64
 11  11      268 non-null    float64
 12  12      268 non-null    float64
 13  13      268 non-null    float64
 14  14      268 non-null    float64
 15  15      268 non-null    float64
 16  16      268 non-null    float64
 17  17      268 non-null    float64
 18  18      268 non-null    float64
 19  19      268 non-null    float64
 20  20      268 non-null    float64
 21  21      268 non-null    float64
 22  22      268 non-null    float64
 23  23      268 non-null    float64
 24  24      268 non-null    float64
 25  25      268 non-null    float64
 26  26      268 non-null    float64
 27  27      268 non-null    float64
 28  28      268 non-null    float64
 29  29      268 non-null    float64
 30  30      268 non-null    float64
 31  31      268 non-null    float64
 32  32      268 non-null    float64
 33  33      268 non-null    float64
 34  34      268 non-null    float64
 35  35      268 non-null    float64
 36  36      268 non-null    float64
 37  37      268 non-null    float64
 38  38      268 non-null    float64
 39  39      268 non-null    float64
 40  40      268 non-null    float64
 41  41      268 non-null    float64
 42  42      268 non-null    float64
 43  43      268 non-null    float64
 44  44      268 non-null    float64
 45  45      268 non-null    float64
 46  46      268 non-null    float64
 47  47      268 non-null    float64
 48  48      268 non-null    float64
 49  49      268 non-null    float64
 50  50      268 non-null    float64
 51  51      268 non-null    float64
 52  52      268 non-null    float64
 53  53      268 non-null    float64
 54  54      268 non-null    float64
 55  55      268 non-null    float64
 56  56      268 non-null    float64
 57  57      268 non-null    float64
 58  58      268 non-null    float64
 59  59      268 non-null    float64
 60  60      268 non-null    float64
 61  61      268 non-null    float64
 62  62      268 non-null    float64
 63  63      268 non-null    float64
 64  64      268 non-null    float64
 65  65      268 non-null    float64
 66  66      268 non-null    float64
dtypes: float64(63), object(4)
memory usage: 140.4+ KB

In [61]:
csvdf7 = df7.to_csv(r'C:\Users\hp\Downloads\API_EG.ELC.RNWX.KH_DS2_en_csv_v2_4356007.csv')
csvdf7